CREATE TABLE IF NOT EXISTS Trades (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    user_id INTEGER NOT NULL,
    symbol VARCHAR(255) NOT NULL,
    shares INTEGER NOT NULL,
    price INTEGER NOT NULL,
    timestamp BIGINT NOT NULL
);
